language: php

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - DEPENDENCIES=""
        - EXECUTE_CS_CHECK=true
        - ARANGODB_VERSION=3.0
    - php: 7.1
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
        - ARANGODB_VERSION=3.0
    - php: 7.1
      env:
        - DEPENDENCIES=""
        - TEST_COVERAGE=true
        - ARANGODB_VERSION=3.1
    - php: 7.1
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
        - ARANGODB_VERSION=3.1
    - php: 7.1
      env:
        - DEPENDENCIES=""
        - ARANGODB_VERSION=3.2
    - php: 7.1
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
        - ARANGODB_VERSION=3.2

addons:
  hosts:
    - arangodb

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - phpenv config-rm xdebug.ini
  - composer self-update
  - composer update --prefer-dist $DEPENDENCIES
  - wget https://www.arangodb.com/repositories/travisCI/setup_arangodb_${ARANGODB_VERSION}.sh
  - chmod 777 setup_arangodb_${ARANGODB_VERSION}.sh
  - ./setup_arangodb_${ARANGODB_VERSION}.sh

script:
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/docheader check src/ tests/; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then php -dzend_extension=xdebug.so ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml; else ./vendor/bin/phpunit; fi

after_success:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/coveralls -v; fi

after_script:
  - killall -s SIGTERM arangod_x86_64

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/61c75218816eebde4486
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
